### ISSUE TITLE
delete, end and home buttons not working in test fields

### ISSUE THREAD

**Issue by chiru9670** [XI-E/LHospital#4]
I see that your UI supports the functions of tab, arrow keys, and enter, but doesn't respond to delete, end and home buttons...
If you haven't, I suggest that you implement the functions of the delete, home and end buttons for the input text fields.

**Comment by arpit-saxena** [comment]
I planned to do it but forgot. Will do

**Comment by arpit-saxena** [comment]
Support added and repository updated.
