### ISSUE TITLE
Problem with phone no. in test.cpp

### ISSUE THREAD

**Issue by chiru9670** [XI-E/LHospital#5]
This is the input when i run test_all() in test.cpp
![input](https://user-images.githubusercontent.com/25587869/32106201-99afd530-bb48-11e7-82ab-cb197cf15894.png)
This is the output...
![output](https://user-images.githubusercontent.com/25587869/32106202-99faab0a-bb48-11e7-95f6-7c2da1c2f1c4.png)

**Comment by arpit-saxena** [comment]
It obviously overflowed. I can add support for unsigned long, if that can handle 10 digits
Otherwise, we just have to store it as a string. @XI-E/xi-e

**Comment by arpit-saxena** [comment]
I'm just leaving this comment to check if the bot on discord will notify us or not

**Comment by sankalpgambhir** [comment]
Overflow shouldn't be possible. We store phone numbers as type 'phone' ( char[10] )

**Comment by arpit-saxena** [comment]
Umm. He ran the test_all() function which declares phn as long

**Comment by sankalpgambhir** [comment]
![image](https://user-images.githubusercontent.com/10048373/32108023-f944a3c2-bb4d-11e7-9c39-074bc2670a86.png)

We declared the base types, why don't you just use those?
I knew 9/10 digit numbers will overflow in turbo, so I made it a string

**Comment by arpit-saxena** [comment]
I'm closing this issue. 
Just store phone as a string a we'll be fine

**Comment by arpit-saxena** [comment]
Another random comment
